#ifndef YS64_THREAD_H
#define YS64_THREAD_H

#define Y_THREAD_ID_IDLE 1
#define Y_THREAD_ID_FAULT 2
#define Y_THREAD_ID_MAIN 3
#define Y_THREAD_ID_DMA 18

#define Y_PRIORITY_IDLE 10
#define Y_PRIORITY_MAIN 10
#define Y_PRIORITY_DMA 18
#define Y_PRIORITY_FAULT OS_PRIORITY_APPMAX

#endif
