name: Build

# Build on every branch push, tag push, and pull request change:
on: [push, pull_request_target]

jobs:
  build_repo:
    name: Build repo
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: [us]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Install package requirements
      run: sudo apt-get install -y make git build-essential clang binutils-mips-linux-gnu gcc-mips-linux-gnu python3 python3-pip clang-format-14 clang-tidy-14

    - name: Install Python dependencies
      run: pip3 install -r requirements.txt

    - name: Get extra dependencies
      uses: actions/checkout@v4
      with:
        repository: ${{ secrets.SECRETREPO }}
        token: ${{ secrets.SECRETTOKEN }}
        path: deps_repo
    - name: Get the dependency
      run: cp deps_repo/yoshis-story/* .

    - name: venv
      run: make venv -j $(nproc) VERSION=${{ mactrix.version }}

    - name: Setup
      run: make setup -j $(nproc) VERSION=${{ matrix.version }}

    # - name: Build libraries
    #   run: make lib -j $(nproc) VERSION=${{ matrix.version }}

    - name: Disassemble and extraction
      run: make extract -j $(nproc) VERSION=${{ matrix.version }}

    - name: Build Rom
      run: make -j $(nproc) WERROR=1 VERSION=${{ matrix.version }}

    - name: Upload frogress
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run: python3 tools/upload_frogress.py ${{ matrix.version }} --apikey ${{ secrets.PROGRESS_API_KEY }}
